export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const GET_INGREDIENTS_LIST = "GET_INGREDIENTS_LIST";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const GET_INGREDIENT_DETAILS = "GET_INGREDIENT_DETAILS";
export const MOVE_INGREDIENT = "MOVE_INGREDIENT";

export const SEND_REQUEST_INGREDIENTS = "SEND_REQUEST_INGREDIENTS";
export const RESPOND_SUCCESS_INGREDIENTS = "RESPOND_SUCCESS_INGREDIENTS";
export const RESPOND_ERROR_INGREDIENTS = "RESPOND_ERROR_INGREDIENTS";
export const SEND_REQUEST_ORDER = "SEND_REQUEST_ORDER";
export const RESPOND_SUCCESS_ORDER = "RESPOND_SUCCESS_ORDER";
export const RESPOND_ERROR_ORDER = "RESPOND_ERROR_ORDER";
