export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const GET_INGREDIENTS_LIST = "GET_INGREDIENTS_LIST";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const GET_INGREDIENT_DETAILS = "GET_INGREDIENT_DETAILS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SUM_ORDER = "SUM_ORDER";
export const INCREASE_INGREDIENT = "INCREASE_INGREDIENT";
export const DECREASE_INGREDIENT = "DECREASE_INGREDIENT";

export const SEND_REQUEST_INGREDIENTS = "SEND_REQUEST_INGREDIENTS";
export const RESPOND_SUCCESS_INGREDIENTS = "RESPOND_SUCCESS_INGREDIENTS";
export const RESPOND_ERROR_INGREDIENTS = "RESPOND_ERROR_INGREDIENTS";

export const SEND_REQUEST_ORDER = "SEND_REQUEST_ORDER";
export const RESPOND_SUCCESS_ORDER = "RESPOND_SUCCESS_ORDER";
export const RESPOND_ERROR_ORDER = "RESPOND_ERROR_ORDER";

export const REGISTER_USER = "REGISTER_USER";
export const SEND_REQUEST_REGISTER = "SEND_REQUEST_REGISTER";
export const RESPOND_SUCCESS_REGISTER = "RESPOND_SUCCESS_REGISTER";
export const RESPOND_ERROR_REGISTER = "RESPOND_ERROR_REGISTER";

export const LOGIN_USER = "LOGIN_USER";
export const SEND_REQUEST_LOGIN = "SEND_REQUEST_LOGIN";
export const RESPOND_SUCCESS_LOGIN = "RESPOND_SUCCESS_LOGIN";
export const RESPOND_ERROR_LOGIN = "RESPOND_ERROR_LOGIN";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const SEND_REQUEST_FORGOT_PASSWORD = "SEND_REQUEST_FORGOT_PASSWORD";
export const RESPOND_SUCCESS_FORGOT_PASSWORD =
  "RESPOND_SUCCESS_FORGOT_PASSWORD";
export const RESPOND_ERROR_FORGOT_PASSWORD = "RESPOND_ERROR_FORGOT_PASSWORD";

export const SEND_REQUEST_USER = "SEND_REQUEST_USER";
export const RESPOND_SUCCESS_USER = "RESPOND_SUCCESS_USER";
export const RESPOND_ERROR_USER = "RESPOND_ERROR_USER";

export const CHANGE_USER = "CHANGE_USER";
export const SEND_REQUEST_CHANGE_USER = "SEND_REQUEST_CHANGE_USER";
export const RESPOND_SUCCESS_CHANGE_USER = "RESPOND_SUCCESS_CHANGE_USER";
export const RESPOND_ERROR_CHANGE_USER = "RESPOND_ERROR_CHANGE_USER";

export const LOGOUT_USER = "LOGOUT_USER";
export const SEND_REQUEST_LOGOUT = "SEND_REQUEST_LOGOUT";
export const RESPOND_SUCCESS_LOGOUT = "RESPOND_SUCCESS_LOGOUT";
export const RESPOND_ERROR_LOGOUT = "RESPOND_ERROR_LOGOUT";

export const SEND_REQUEST_REFRESH_TOKEN = "SEND_REQUEST_REFRESH_TOKEN";
export const RESPOND_SUCCESS_REFRESH_TOKEN = "RESPOND_SUCCESS_REFRESH_TOKEN";
export const RESPOND_ERROR_REFRESH_TOKEN = "RESPOND_ERROR_REFRESH_TOKEN";
