// ORDERING
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const GET_INGREDIENTS_LIST: "GET_INGREDIENTS_LIST" =
  "GET_INGREDIENTS_LIST";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const GET_INGREDIENT_DETAILS: "GET_INGREDIENT_DETAILS" =
  "GET_INGREDIENT_DETAILS";
export const SET_INGREDIENTS: "SET_INGREDIENTS" = "SET_INGREDIENTS";
export const SUM_ORDER: "SUM_ORDER" = "SUM_ORDER";
export const INCREASE_INGREDIENT: "INCREASE_INGREDIENT" = "INCREASE_INGREDIENT";
export const DECREASE_INGREDIENT: "DECREASE_INGREDIENT" = "DECREASE_INGREDIENT";

export const SEND_REQUEST_INGREDIENTS: "SEND_REQUEST_INGREDIENTS" =
  "SEND_REQUEST_INGREDIENTS";
export const RESPOND_SUCCESS_INGREDIENTS: "RESPOND_SUCCESS_INGREDIENTS" =
  "RESPOND_SUCCESS_INGREDIENTS";
export const RESPOND_ERROR_INGREDIENTS: "RESPOND_ERROR_INGREDIENTS" =
  "RESPOND_ERROR_INGREDIENTS";

export const SEND_REQUEST_ORDER: "SEND_REQUEST_ORDER" = "SEND_REQUEST_ORDER";
export const RESPOND_SUCCESS_ORDER: "RESPOND_SUCCESS_ORDER" =
  "RESPOND_SUCCESS_ORDER";
export const RESPOND_ERROR_ORDER: "RESPOND_ERROR_ORDER" = "RESPOND_ERROR_ORDER";

// MAKE ORDER
export const SEND_ORDER: "SEND_ORDER" = "SEND_ORDER";
export const SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS" = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_ERROR: "SEND_ORDER_ERROR" = "SEND_ORDER_ERROR";

// GET ORDER
export const GET_ORDER: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR: "GET_ORDER_ERROR" = "GET_ORDER_ERROR";

// ORDER INFO
export const SEND_REQUEST_ORDER_INFO = "SEND_REQUEST_ORDER_INFO";
export const GET_ORDER_INFO_SUCCESS = "GET_ORDER_INFO_SUCCESS";
export const GET_ORDER_INFO_ERROR = "GET_ORDER_INFO_ERROR";

// USER
export const SEND_REQUEST_REGISTER: "SEND_REQUEST_REGISTER" =
  "SEND_REQUEST_REGISTER";
export const RESPOND_SUCCESS_REGISTER: "RESPOND_SUCCESS_REGISTER" =
  "RESPOND_SUCCESS_REGISTER";
export const RESPOND_ERROR_REGISTER: "RESPOND_ERROR_REGISTER" =
  "RESPOND_ERROR_REGISTER";

export const SEND_REQUEST_LOGIN: "SEND_REQUEST_LOGIN" = "SEND_REQUEST_LOGIN";
export const RESPOND_SUCCESS_LOGIN: "RESPOND_SUCCESS_LOGIN" =
  "RESPOND_SUCCESS_LOGIN";
export const RESPOND_ERROR_LOGIN: "RESPOND_ERROR_LOGIN" = "RESPOND_ERROR_LOGIN";

export const SEND_REQUEST_FORGOT_PASSWORD: "SEND_REQUEST_FORGOT_PASSWORD" =
  "SEND_REQUEST_FORGOT_PASSWORD";
export const RESPOND_SUCCESS_FORGOT_PASSWORD: "RESPOND_SUCCESS_FORGOT_PASSWORD" =
  "RESPOND_SUCCESS_FORGOT_PASSWORD";
export const RESPOND_ERROR_FORGOT_PASSWORD: "RESPOND_ERROR_FORGOT_PASSWORD" =
  "RESPOND_ERROR_FORGOT_PASSWORD";

export const SEND_REQUEST_RESET_PASSWORD: "SEND_REQUEST_RESET_PASSWORD" =
  "SEND_REQUEST_RESET_PASSWORD";
export const RESPOND_SUCCESS_RESET_PASSWORD: "RESPOND_SUCCESS_FORGOT_PASSWORD" =
  "RESPOND_SUCCESS_FORGOT_PASSWORD";
export const RESPOND_ERROR_RESET_PASSWORD: "RESPOND_ERROR_RESET_PASSWORD" =
  "RESPOND_ERROR_RESET_PASSWORD";

export const SEND_REQUEST_USER: "SEND_REQUEST_USER" = "SEND_REQUEST_USER";
export const RESPOND_SUCCESS_USER: "RESPOND_SUCCESS_USER" =
  "RESPOND_SUCCESS_USER";
export const RESPOND_ERROR_USER: "RESPOND_ERROR_USER" = "RESPOND_ERROR_USER";

export const SEND_REQUEST_CHANGE_USER: "SEND_REQUEST_CHANGE_USER" =
  "SEND_REQUEST_CHANGE_USER";
export const RESPOND_SUCCESS_CHANGE_USER: "RESPOND_SUCCESS_CHANGE_USER" =
  "RESPOND_SUCCESS_CHANGE_USER";
export const RESPOND_ERROR_CHANGE_USER: "RESPOND_ERROR_CHANGE_USER" =
  "RESPOND_ERROR_CHANGE_USER";

export const SEND_REQUEST_LOGOUT: "SEND_REQUEST_LOGOUT" = "SEND_REQUEST_LOGOUT";
export const RESPOND_SUCCESS_LOGOUT: "RESPOND_SUCCESS_LOGOUT" =
  "RESPOND_SUCCESS_LOGOUT";
export const RESPOND_ERROR_LOGOUT: "RESPOND_ERROR_LOGOUT" =
  "RESPOND_ERROR_LOGOUT";

// WS
export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_STOP: "WS_CONNECTION_STOP" = "WS_CONNECTION_STOP";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_ORDERS: "WS_GET_ORDERS" = "WS_GET_ORDERS";
export const WS_SEND_ORDERS: "WS_SEND_ORDERS" = "WS_SEND_ORDERS";
